import * as path from 'path';
import * as fs from 'fs-extra';
import inquirer from 'inquirer';

const HOME = process.env.HOME || '';
const FUSKA_CONFIG_DIR = path.join(HOME, '.config/fuska');
const FUSKA_CONFIG_FILE = path.join(FUSKA_CONFIG_DIR, 'fuska.jsonc');

export type ProviderType = 'opencode' | 'claude';

export interface ProviderConfig {
  provider: ProviderType;
}

/**
 * Strip JSONC comments from content before parsing.
 * Handles single-line // comments and multi-line block comments.
 */
function stripJsoncComments(content: string): string {
  // Remove block comments /* ... */
  let result = content.replace(/\/\*[\s\S]*?\*\//g, '');
  // Remove line comments // ...
  result = result.replace(/\/\/.*$/gm, '');
  return result.trim();
}

/**
 * Detect which AI providers are installed by checking their config directories.
 */
export async function detectInstalledProviders(): Promise<('opencode' | 'claude')[]> {
  const providers: ('opencode' | 'claude')[] = [];
  
  const opencodeConfig = path.join(HOME, '.config/opencode');
  const claudeConfig = path.join(HOME, '.claude');
  
  if (await fs.pathExists(opencodeConfig)) {
    providers.push('opencode');
  }
  
  if (await fs.pathExists(claudeConfig)) {
    providers.push('claude');
  }
  
  return providers;
}

/**
 * Read the provider configuration from fuska.jsonc.
 * Returns null if the file doesn't exist or is invalid.
 */
export async function readProviderConfig(): Promise<ProviderConfig | null> {
  if (!await fs.pathExists(FUSKA_CONFIG_FILE)) {
    return null;
  }
  
  try {
    const content = await fs.readFile(FUSKA_CONFIG_FILE, 'utf-8');
    const stripped = stripJsoncComments(content);
    const config = JSON.parse(stripped) as ProviderConfig;
    
    // Validate the provider value
    if (config.provider !== 'opencode' && config.provider !== 'claude') {
      return null;
    }
    
    return config;
  } catch (e) {
    // Invalid JSON or other error
    return null;
  }
}

/**
 * Write the provider configuration to fuska.jsonc.
 * Creates the config directory if it doesn't exist.
 */
export async function writeProviderConfig(config: ProviderConfig): Promise<void> {
  await fs.ensureDir(FUSKA_CONFIG_DIR);
  
  const content = `// Fuska CLI Configuration
// Generated by fuska provider command

{
  "provider": "${config.provider}"
}
`;
  
  await fs.writeFile(FUSKA_CONFIG_FILE, content, 'utf-8');
}

// Cache the selected provider to avoid re-prompting during a CLI session
let cachedProvider: 'opencode' | 'claude' | null = null;

/**
 * Get the configured provider, or prompt the user if not configured.
 * Caches the selection for the current session.
 */
export async function getOrPromptProvider(): Promise<'opencode' | 'claude'> {
  // Return cached provider if available
  if (cachedProvider) {
    return cachedProvider;
  }
  
  // Try to read existing config
  const config = await readProviderConfig();
  if (config) {
    cachedProvider = config.provider;
    return cachedProvider;
  }
  
  // No config - prompt user
  const installed = await detectInstalledProviders();
  
  if (installed.length === 0) {
    console.error('No AI provider found. Install opencode or claude first.');
    console.error('  opencode: https://github.com/opencode-ai/opencode');
    console.error('  claude: https://claude.ai/code');
    process.exit(1);
  }
  
  // Determine default (prefer first installed)
  const defaultProvider = installed[0];
  
  // If only one provider is installed, use it without prompting
  if (installed.length === 1) {
    console.log(`Using ${defaultProvider} (only installed provider)`);
    await writeProviderConfig({ provider: defaultProvider });
    cachedProvider = defaultProvider;
    return cachedProvider;
  }
  
  // Multiple providers - prompt user
  const { provider } = await inquirer.prompt([
    {
      type: 'list',
      name: 'provider',
      message: 'Which AI provider should fuska use?',
      choices: installed.map(p => ({
        name: p,
        value: p
      })),
      default: defaultProvider
    }
  ]);
  
  await writeProviderConfig({ provider });
  console.log(`Provider set to ${provider} (${FUSKA_CONFIG_FILE})`);
  
  cachedProvider = provider as 'opencode' | 'claude';
  return cachedProvider;
}
